name: Moderation
author: Trixkz
version: 1.0
main: xyz.trixkz.moderation.Main

commands:
  rank:
  grant:
  warn:
  kick:
  mute:
  tempmute:
  ban:
  tempban:
  blacklist:
  history:
  unmute:
  unban: